[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
common.workspace = true
arboard.workspace = true
chrono.workspace = true
directories.workspace = true
eframe.workspace = true
global-hotkey.workspace = true
image.workspace = true
imageproc.workspace = true
ab_glyph.workspace = true
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
single-instance.workspace = true
thiserror.workspace = true
tray-icon.workspace = true
uuid.workspace = true
winit.workspace = true
xcap.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", features = [
  "NSApplication",
  "NSColor",
  "NSCursor",
  "NSGraphics",
  "NSGraphicsContext",
  "NSImage",
  "NSImageRep",
  "NSPanel",
  "NSRunningApplication",
  "NSScreen",
  "NSPasteboard",
  "NSView",
  "NSWindow",
  "NSWorkspace",
  "objc2-quartz-core",
] }
block2 = "0.6.2"
objc2-core-foundation = { version = "0.3.2", features = [
  "CFData",
] }
objc2-core-services = { version = "0.3.2", default-features = false, features = [
  "AE",
  "AEDataModel",
  "AppleEvents",
  "objc2",
] }
objc2-core-graphics = { version = "0.3.2", features = [
  "CGBitmapContext",
  "CGColorSpace",
  "CGContext",
  "CGDirectDisplay",
  "CGEvent",
  "CGGeometry",
  "CGImage",
  "CGWindow",
] }
objc2-foundation = { version = "0.3.2", features = [
  "NSArray",
  "NSData",
  "NSDictionary",
  "NSAppleEventDescriptor",
  "NSAppleEventManager",
  "NSObject",
  "NSString",
  "NSURL",
  "NSValue",
  "objc2-core-services",
] }
objc2-image-io = { version = "0.3.2", default-features = false, features = [
  "CGImageDestination",
  "CGImageSource",
  "objc2-core-graphics",
  "std",
] }
objc2-quartz-core = { version = "0.3.2", features = ["CALayer", "CATransaction"] }
objc2-screen-capture-kit = { version = "0.3.2", default-features = false, features = [
  "SCError",
  "SCScreenshotManager",
  "SCShareableContent",
  "SCStream",
  "block2",
  "libc",
  "objc2-core-foundation",
  "objc2-core-graphics",
  "std",
] }
smappservice-rs = "0.1.3"

[package.metadata.bundle]
name = "RS Board"
identifier = "com.linjiajian.rs-board"
category = "public.app-category.productivity"
icon = ["assets/AppIcon.icns"]
osx_minimum_system_version = "13.0"
osx_info_plist_exts = ["assets/macos-info-plist-ext.xml"]
copyright = "Copyright (c) 2026 smooth-cat"
