#!/usr/bin/env bash
set -euo pipefail

RS_BOARD_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RS_BOARD_ROOT="$(cd "$RS_BOARD_SCRIPT_DIR/.." && pwd)"
RS_BOARD_EXPECTED_ABOUT_VERSION="cargo-about 0.9.1"
RS_BOARD_TARGET="aarch64-apple-darwin"
RS_BOARD_EPAINT_FONTS_VERSION="0.36.0"
RS_BOARD_NOTICES="$RS_BOARD_ROOT/crates/app/assets/THIRD_PARTY_NOTICES.txt"
RS_BOARD_NOTO_LICENSE="$RS_BOARD_ROOT/distribution/NotoSansSC-OFL.txt"
RS_BOARD_NOTO_FONT="$RS_BOARD_ROOT/crates/app/assets/NotoSansSC-Regular.otf"
RS_BOARD_NOTO_SHA256="faa6c9df652116dde789d351359f3d7e5d2285a2b2a1f04a2d7244df706d5ea9"

fail() {
  echo "error: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

verify_sha256() {
  local file="$1"
  local expected="$2"
  local actual
  actual="$(shasum -a 256 "$file" | awk '{print $1}')"
  [[ "$actual" == "$expected" ]] || fail "unexpected SHA-256 for $file"
}

[[ $# -le 1 ]] || fail "usage: $0 [--check]"
RS_BOARD_CHECK_ONLY=0
if [[ $# -eq 1 ]]; then
  [[ "$1" == "--check" ]] || fail "usage: $0 [--check]"
  RS_BOARD_CHECK_ONLY=1
fi

for command_name in cargo cargo-about cmp jq shasum; do
  require_command "$command_name"
done
[[ "$(cargo-about --version)" == "$RS_BOARD_EXPECTED_ABOUT_VERSION" ]] \
  || fail "expected $RS_BOARD_EXPECTED_ABOUT_VERSION"

for required_file in \
  "$RS_BOARD_ROOT/Cargo.lock" \
  "$RS_BOARD_ROOT/distribution/about.toml" \
  "$RS_BOARD_ROOT/distribution/about.hbs" \
  "$RS_BOARD_NOTO_LICENSE" \
  "$RS_BOARD_NOTO_FONT"; do
  [[ -s "$required_file" ]] || fail "required file is missing or empty: $required_file"
done
verify_sha256 "$RS_BOARD_NOTO_FONT" "$RS_BOARD_NOTO_SHA256"

RS_BOARD_EPAINT_MANIFEST="$(
  cd "$RS_BOARD_ROOT"
  cargo metadata --locked --offline --format-version 1 \
    | jq -er --arg version "$RS_BOARD_EPAINT_FONTS_VERSION" \
      '[.packages[] | select(.name == "epaint_default_fonts" and .version == $version)]
       | if length == 1 then .[0].manifest_path else error("expected one epaint_default_fonts package") end'
)"
RS_BOARD_EPAINT_FONT_DIR="$(dirname "$RS_BOARD_EPAINT_MANIFEST")/fonts"

verify_sha256 "$RS_BOARD_EPAINT_FONT_DIR/Hack-Regular.txt" \
  "47c0cccbeec7e8614548cc485588b28149e7874188df5f41b36efebcee285c87"
verify_sha256 "$RS_BOARD_EPAINT_FONT_DIR/OFL.txt" \
  "6a73f9541c2de74158c0e7cf6b0a58ef774f5a780bf191f2d7ec9cc53efe2bf2"
verify_sha256 "$RS_BOARD_EPAINT_FONT_DIR/UFL.txt" \
  "2f0015108d68627bd788d313f529c21ff4da2c2c42a5e1f3883acc83480f9002"
verify_sha256 "$RS_BOARD_EPAINT_FONT_DIR/emoji-icon-font-mit-license.txt" \
  "b9d2c1d909aa149996fd4c91dcb92b2362a04431640c1d200959da94caf8cde1"

RS_BOARD_TEMP_DIR="$(mktemp -d /tmp/rs-board-notices.XXXXXX)"
RS_BOARD_RUST_NOTICES="$RS_BOARD_TEMP_DIR/rust-notices.txt"
RS_BOARD_RAW_NOTICES="$RS_BOARD_TEMP_DIR/THIRD_PARTY_NOTICES.raw.txt"
RS_BOARD_GENERATED_NOTICES="$(mktemp "$RS_BOARD_ROOT/crates/app/assets/.THIRD_PARTY_NOTICES.XXXXXX")"

cleanup() {
  rm -rf "$RS_BOARD_TEMP_DIR"
  rm -f "$RS_BOARD_GENERATED_NOTICES"
}
trap cleanup EXIT

(
  cd "$RS_BOARD_ROOT"
  cargo about generate distribution/about.hbs \
    --config distribution/about.toml \
    --manifest-path crates/app/Cargo.toml \
    --target "$RS_BOARD_TARGET" \
    --locked \
    --offline \
    --fail \
    --output-file "$RS_BOARD_RUST_NOTICES"
)

{
  printf '%s\n' \
    'RS Board Third-Party Notices' \
    '============================' \
    '' \
    'This file is generated by scripts/generate-third-party-notices.sh.' \
    'It contains notices for the locked Apple Silicon Rust dependency graph' \
    'and for fonts embedded in the application binary.' \
    '' \
    'Noto Sans SC Regular' \
    '--------------------' \
    '' \
    'File: NotoSansSC-Regular.otf' \
    'Version: 2.004' \
    'Source: https://github.com/notofonts/noto-cjk/blob/main/Sans/SubsetOTF/SC/NotoSansSC-Regular.otf' \
    "SHA-256: $RS_BOARD_NOTO_SHA256" \
    'Copyright 2014-2021 Adobe (http://www.adobe.com/).' \
    'Noto is a trademark of Google Inc.' \
    'License: SIL Open Font License 1.1' \
    ''
  cat "$RS_BOARD_NOTO_LICENSE"
  printf '\n\n'
  cat "$RS_BOARD_RUST_NOTICES"
  printf '%s\n' \
    '' \
    'epaint_default_fonts original font notices' \
    '-------------------------------------------' \
    '' \
    'The epaint_default_fonts 0.36.0 crate embeds Hack Regular, Ubuntu Light,' \
    'Noto Emoji Regular, and emoji-icon-font. The following files are copied' \
    'from that locked crate after their SHA-256 hashes are verified.' \
    ''

  for notice_name in \
    Hack-Regular.txt \
    OFL.txt \
    UFL.txt \
    emoji-icon-font-mit-license.txt; do
    printf '%s\n' \
      '================================================================================' \
      "epaint_default_fonts 0.36.0/fonts/$notice_name" \
      ''
    cat "$RS_BOARD_EPAINT_FONT_DIR/$notice_name"
    printf '\n\n'
  done
} >"$RS_BOARD_RAW_NOTICES"

tr -d '\r' <"$RS_BOARD_RAW_NOTICES" \
  | sed 's/[[:blank:]]*$//' \
  | awk '
      $0 == "" { blank_lines++; next }
      {
        while (blank_lines > 0) {
          print ""
          blank_lines--
        }
        print
      }
    ' >"$RS_BOARD_GENERATED_NOTICES"
chmod 0644 "$RS_BOARD_GENERATED_NOTICES"

if [[ "$RS_BOARD_CHECK_ONLY" == "1" ]]; then
  [[ -f "$RS_BOARD_NOTICES" ]] || fail "generated notices are missing: $RS_BOARD_NOTICES"
  cmp -s "$RS_BOARD_GENERATED_NOTICES" "$RS_BOARD_NOTICES" \
    || fail "THIRD_PARTY_NOTICES.txt is stale; run $0"
  echo "verified: $RS_BOARD_NOTICES"
else
  mv "$RS_BOARD_GENERATED_NOTICES" "$RS_BOARD_NOTICES"
  echo "generated: $RS_BOARD_NOTICES"
fi
